#!/usr/bin/env node
// Generate _workflows.md — the registry of workflows you have at hand.
// Single source of truth = each workflow's `export const meta` block (mirrors how
// _graph.md is generated from the vault). Run after adding or editing a workflow:
//   node .claude/workflows/_generate_registry.mjs
import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const PROJECT = process.env.CLAUDE_PROJECT_DIR || '/Users/alexcohen/InvestmentVault'
const WF_DIR = join(PROJECT, '.claude', 'workflows')

// Brace-match the meta object literal, ignoring braces inside strings.
function extractMeta(src) {
  const i = src.indexOf('const meta')
  if (i < 0) return null
  const start = src.indexOf('{', i)
  if (start < 0) return null
  let depth = 0, inStr = null, esc = false
  for (let j = start; j < src.length; j++) {
    const c = src[j]
    if (inStr) {
      if (esc) esc = false
      else if (c === '\\') esc = true
      else if (c === inStr) inStr = null
      continue
    }
    if (c === '"' || c === "'" || c === '`') inStr = c
    else if (c === '{') depth++
    else if (c === '}') {
      if (--depth === 0) {
        try { return (0, eval)('(' + src.slice(start, j + 1) + ')') } catch { return null }
      }
    }
  }
  return null
}

const esc = (s) => String(s || '').replace(/\|/g, '\\|')
const files = readdirSync(WF_DIR).filter((f) => f.endsWith('.js') && !f.startsWith('_')).sort()
const rows = []
for (const f of files) {
  const meta = extractMeta(readFileSync(join(WF_DIR, f), 'utf8'))
  if (meta && meta.name) rows.push({ file: f, ...meta })
}

const today = new Date().toISOString().slice(0, 10)
let md = `---
date: ${today}
tags: [meta, workflows, registry]
---
# Workflows Registry

> Auto-generated by \`.claude/workflows/_generate_registry.mjs\` — re-run after adding or editing a workflow. Workflows are multi-agent orchestrations (heavier than skills); each lives at \`.claude/workflows/<name>.js\` and is invoked by asking Claude to run it. First run prompts a usage warning (they can spawn many agents); watch progress with \`/workflows\`.

## Available (${rows.length})

| Workflow | What it does | When to use |
|---|---|---|
`
for (const r of rows) md += `| \`${r.name}\` | ${esc(r.description)} | ${esc(r.whenToUse || '—')} |\n`

md += `\n## Details\n`
for (const r of rows) {
  const phases = (r.phases || []).map((p) => p.title).join(' → ') || '—'
  md += `\n### ${r.name}\n`
  md += `- **File**: \`.claude/workflows/${r.file}\`\n`
  md += `- **Does**: ${r.description || ''}\n`
  md += `- **Phases**: ${phases}\n`
  md += `- **Invoke**: ask *"run the ${r.name} workflow"* — or \`Workflow({name:"${r.name}"})\` / \`Workflow({scriptPath:".claude/workflows/${r.file}"})\`\n`
}

writeFileSync(join(PROJECT, '_workflows.md'), md)
console.log(`wrote _workflows.md — ${rows.length} workflow(s): ${rows.map((r) => r.name).join(', ') || '(none)'}`)
