#!/usr/bin/env python3
"""Publish the clean final /lint report as a dated vault note.

The scheduled runner calls `claude -p "/lint" --output-format json`; this extracts
the final report text from that envelope and writes it to a dated markdown note in
`Daily Intel/`, so the headless weekly run is actually visible in Obsidian (morning
scan) instead of buried in a raw log. Defensive: on any extraction failure it still
writes a note pointing at the log, so a run is never silently invisible.

Usage: publish-lint-note.py <json-file> <note-path> <YYYY-MM-DD>
"""
import sys, json, os


def extract_result(raw):
    """Pull the final assistant text from a `-p --output-format json` envelope.
    Handles both the single result object and a stream-json array of events."""
    try:
        data = json.loads(raw)
    except Exception:
        return None
    if isinstance(data, dict):
        for k in ("result", "text", "content"):
            v = data.get(k)
            if isinstance(v, str) and v.strip():
                return v
        return None
    if isinstance(data, list):
        for item in reversed(data):
            if isinstance(item, dict):
                for k in ("result", "text"):
                    v = item.get(k)
                    if isinstance(v, str) and v.strip():
                        return v
    return None


def main():
    if len(sys.argv) < 4:
        print("usage: publish-lint-note.py <json-file> <note-path> <YYYY-MM-DD>")
        sys.exit(2)
    json_file, note_path, report_date = sys.argv[1], sys.argv[2], sys.argv[3]

    raw = ""
    try:
        with open(json_file, encoding="utf-8") as f:
            raw = f.read()
    except OSError:
        raw = ""

    report = extract_result(raw)

    os.makedirs(os.path.dirname(note_path), exist_ok=True)
    header = (
        f"---\n"
        f"date: {report_date}\n"
        f"tags: [meta, health, lint]\n"
        f"source: scheduled /lint (launchd com.investmentvault.lint)\n"
        f"---\n\n"
        f"# Vault Health — /lint — {report_date}\n\n"
        f"> Auto-generated by the weekly scheduled `/lint`. Read-only surface; "
        f"prune via `/clean daily-intel`.\n\n"
    )
    if report:
        body = report.strip()
        tag = "report"
    else:
        body = (
            "⚠️ Could not extract the lint report from the run output.\n\n"
            "Check the raw run log at `.claude/schedule/logs/lint.log` and the JSON "
            f"envelope at `{os.path.relpath(json_file, os.path.dirname(note_path))}`."
        )
        tag = "FALLBACK (extraction failed)"

    with open(note_path, "w", encoding="utf-8") as f:
        f.write(header + body + "\n")
    print(f"published lint note [{tag}]: {note_path}")


if __name__ == "__main__":
    main()
